linters-settings:
  dupl:
    threshold: 150
  funlen:
    lines: 150
    statements: 70
  gci:
    local-prefixes: github.com/golangci/golangci-lint
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 25
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  govet:
    check-shadowing: true
  lll:
    line-length: 250
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gofmt
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - structcheck
    - unconvert
    - varcheck
    - whitespace
    - asciicheck
    - depguard
    - exportloopref
    - funlen
    - gochecknoglobals
    - gocognit
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - nestif
    - prealloc
    - typecheck
    - whitespace

issues:
  exclude-rules:
      
    - path: _test\.go
      linters:
        - bodyclose


run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 5
  tests: true

  skip-dirs:
    - tests
    - tools

  # Enables skipping of directories:
  # - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  # Default: true
  skip-dirs-use-default: false
  modules-download-mode: readonly
  go: "1.18"


